---
- hosts: satellite_registration
  tasks:

   - name: Update hostname
     hostname:
        name: "{{ ansible_fqdn }}"

   - name: Get SSL certificate
     get_url:
       url: https://SatelliteFQDN/pub/RHN-ORG-TRUSTED-SSL-CERT
       dest: /usr/share/rhn
       validate_certs: False

   - name: Add an entry in up2date file
     lineinfile:
        path: /etc/sysconfig/rhn/up2date
        regexp: '^serverURL'
        line: 'serverURL=https://SatelliteFQDN/XMLRPC'
        state: present

   - name: Register server to RedHat Satellite
     shell: "rhnreg_ks --username=usernametologinsatellite --password=password --force"

   - name: Install packages
     yum:
       name: "{{ samba }}"
     vars:
       samba:
       - samba-client 
       - samba-winbind 
       - samba-winbind-clients 
       - krb5-workstation 
       - ntp
     ignore_errors: yes

   - shell: yum install -y samba-client samba-winbind samba-winbind-clients krb5-workstation ntp
     args:
       warn: false 

   - name: Configure NTP
     template: 
       src: /var/lib/awx/projects/rhel_server_registration/ntp.j2
       dest: /etc/ntp.conf
       owner: root
       group: root
       mode: 0644
       backup: yes

   - name: Restart NTP service
     service:
       name: ntpd
       state: restarted
       enabled: yes

   - name: Configire Samba
     template:
       src: /var/lib/awx/projects/rhel_server_registration/smb.j2
       dest: /etc/samba/smb.conf
       owner: root
       group: root
       mode: 0644
       backup: yes

   - name: Configure Kerberos
     template: 
       src: /var/lib/awx/projects/rhel_server_registration/krb5.j2
       dest: /etc/krb5.conf
       owner: root
       group: root
       mode: 0644
       backup: yes 
     
   - name: Join AD
     shell: net ads join -e -U appdev\\username%password 
     register: ansible_password
   - debug: var=ansible_password

   - name: Restart winbind
     service:
       name: winbind
       state: restarted
       enabled: yes

   - name: Enable winbind
     shell: authconfig --enablewinbind --enablewinbindauth  --enablemkhomedir --update
